### ISSUE TITLE
Webpack error

### ISSUE THREAD

**Issue by nsreenan** [SPCSR/HelperFunctions#2]
I am getting the following error when trying to compile with webpack. Any insight would be greatly appreciated.

ts-loader: Using typescript@1.8.10
Hash: b048a9be543d5c383db8
Version: webpack 1.14.0
Time: 243ms
    + 1 hidden modules

ERROR in ./search.queryVariableInjector.ts
Module build failed: TypeError: Path must be a string. Received undefined
    at assertPath (path.js:7:11)
    at Object.dirname (path.js:695:5)
    at ensureTypeScriptInstance (C:\Users\nsreenan\Desktop\HelperFunctions\SPO-Search-Improvements\node_modules\ts-loader\index.js:156:103)
    at Object.loader (C:\Users\nsreenan\Desktop\HelperFunctions\SPO-Search-Improvements\node_modules\ts-loader\index.js:403:14)

**Comment by estruyf** [comment]
This should now be fixed with the latest commit. In the "early" days of webpack and TypeScript it didn't require for you to have a tsconfig file in the project. With the latest packages, this is required and because it was missing in the project, webpack failed to bundle. When you download the  latest commit, you will see it has a tsconfig file and webpack should now be able to bundle again.

**Comment by nsreenan** [comment]
Thanks Elio,

That seemed to do the trick and I think I have it going now, will test it out a bit more tomorrow. I think this will be very helpful, thank you!

Neil
